BEGIN TRANSACTION;

DROP TABLE IF EXISTS Flashcards;
DROP TABLE IF EXISTS Stacks;
DROP TABLE IF EXISTS Study_Sessions;

CREATE TABLE Stacks (
id INT IDENTITY PRIMARY KEY,
stackName NVARCHAR(50) NOT NULL UNIQUE);

CREATE TABLE Flashcards (
id INT IDENTITY PRIMARY KEY,
answer NVARCHAR(50),
prompt NVARCHAR(200) UNIQUE,
stackId INT NOT NULL FOREIGN KEY REFERENCES Stacks);

CREATE TABLE Study_Sessions (
id INT IDENTITY PRIMARY KEY,
date NVARCHAR(15) NOT NULL,
score INT NOT NULL,
stackId INT NOT NULL FOREIGN KEY REFERENCES Stacks);

COMMIT;